repositories {
	exclusiveContent {
		forRepository { maven { url = "https://api.modrinth.com/maven" } }
		filter { includeGroup "maven.modrinth" }
	}
}

dependencies {
	implementation "maven.modrinth:modmenu:${project.modmenu_version}"
	productionRuntimeMods "maven.modrinth:modmenu:${project.modmenu_version}"
}
