repositories {
	exclusiveContent {
		forRepository { maven { url = "https://maven.terraformersmc.com/releases/" } }
		filter { includeGroup "com.terraformersmc" }
	}
}

dependencies {
	// ModMenu
	implementation("com.terraformersmc:modmenu:${rootProject.modmenu_version}") { exclude group: "net.fabricmc.fabric-api" }
	productionRuntimeMods("com.terraformersmc:modmenu:${rootProject.modmenu_version}") { exclude group: "net.fabricmc.fabric-api" }
}
