# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
org.gradle.vfs.watch=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
java_version=25

# Mod Properties
mod_side=client
mod_version=1.0.0
mod_id=textureatlasgenerator
maven_group=io.github.brainage04.textureatlasgenerator
archives_base_name=textureatlasgenerator
mod_name=TextureAtlasGenerator

# Dependencies
fabric_api_version=0.156.0+26.2
modmenu_version=20.0.1
fabricmoddingconventions_version=2.4.1

# Multi-loader Properties
architectury_loom_version=1.17.491
neoforge_version=26.2.0.41-beta
