plugins {
	id 'dev.architectury.loom-no-remap'
	id 'dev.architectury.loom'
}


loom {
	accessWidenerPath = project.file('src/main/resources/textureatlasgenerator.accesswidener')
}

dependencies {
	minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
	compileOnly "net.fabricmc:fabric-loader:${rootProject.loader_version}"
}
